version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sensor_data
    ports:
      - "5432:5432"
  
  processor:
    build: ./processor
    depends_on:
      - kafka
  
  ui:
    build: ./ui
    ports:
      - "5000:5000"

