version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sensor_data
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  sensor_emulator:
    build: ./sensor_emulator
    depends_on:
      - mqtt

  data_processor:
    build: ./data_processor
    depends_on:
      - mqtt
  
  ui:
    build: ./ui
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: bash -c "sleep 10 && flask run --host=0.0.0.0 --port=5000"
