apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-processor
  template:
    metadata:
      labels:
        app: iot-processor
    spec:
      containers:
      - name: processor
        image: myrepo/iot-sensor:latest
        ports:
        - containerPort: 5000

